//! Team-catalog CLI handlers backing `orchestrator team` subcommands.
//!
//! Each function takes a `&mut ConnectionManager` plus the parsed args, prints
//! structured JSON to stdout, and returns `Result<()>`. The binary glues clap
//! to these — keep them pure (no global state, no exit-on-error). For the
//! register/duplicate path the function returns `Err(Error::Config(...))`
//! after printing so the caller can map it to a non-zero exit.

use crate::team_validator::{self, TeamValidationViolation};
use crate::{redis_io, Error, Result};
use orchestrator_types::{TeamTopology, VersionedRef};
use redis::aio::ConnectionManager;
use serde_json::json;
use std::path::Path;

/// `orchestrator team list` — print one `{"name":"…","version":N}` per line.
pub async fn list(conn: &mut ConnectionManager) -> Result<()> {
    let pairs = redis_io::list_teams(conn).await?;
    for (name, version) in pairs {
        let line = json!({ "name": name.0, "version": version });
        println!("{line}");
    }
    Ok(())
}

/// `orchestrator team show <name> <version>` — pretty-printed `TeamTopology`.
pub async fn show(conn: &mut ConnectionManager, name: &str, version: u32) -> Result<()> {
    let r = VersionedRef::new(name, version);
    let team = redis_io::fetch_team(conn, &r).await?;
    println!("{}", serde_json::to_string_pretty(&team)?);
    Ok(())
}

/// `orchestrator team register <file>` — parse, validate, atomically register.
///
/// Sequence:
/// 1. Read the file and deserialize it as `TeamTopology` (strict serde —
///    unknown fields are rejected here as a `Vocabulary`-equivalent violation).
/// 2. Fetch the role registry via `redis_io::list_roles`.
/// 3. Run `team_validator::validate`; on any violations, print
///    `{"registered":false,"violations":[…]}` and return Err.
/// 4. `register_team_strict` atomically; print outcome and (on already-exists)
///    return Err so the caller exits non-zero.
pub async fn register(conn: &mut ConnectionManager, file: &Path) -> Result<()> {
    let text = tokio::fs::read_to_string(file).await?;
    let team: TeamTopology = match serde_json::from_str::<TeamTopology>(&text) {
        Ok(t) => t,
        Err(e) => {
            let v = vocabulary_violation_json(&e);
            print_violations_raw(false, &[v]);
            return Err(Error::Config(format!("vocabulary: {e}")));
        }
    };

    let registered_roles = redis_io::list_roles(conn).await?;
    let violations = team_validator::validate(&team, &registered_roles);
    if !violations.is_empty() {
        let arr: Vec<_> = violations.iter().map(violation_to_json).collect();
        print_violations_raw(false, &arr);
        return Err(Error::Config(format!(
            "team {} v{} failed validation: {} violation(s)",
            team.name.0,
            team.version,
            violations.len()
        )));
    }

    match redis_io::register_team_strict(conn, &team).await? {
        redis_io::RegisterOutcome::Registered => {
            println!(
                "{}",
                json!({
                    "registered": true,
                    "name": team.name.0,
                    "version": team.version,
                })
            );
            Ok(())
        }
        redis_io::RegisterOutcome::AlreadyExists => {
            println!(
                "{}",
                json!({
                    "registered": false,
                    "reason": "already_exists",
                    "name": team.name.0,
                    "version": team.version,
                })
            );
            Err(Error::Config(format!(
                "team {} v{} already exists",
                team.name.0, team.version
            )))
        }
    }
}

/// `orchestrator team schema` — print the JSON schema of `TeamTopology`.
///
/// Offline (no Redis). Prints the schema generated by `schemars::schema_for!`
/// as pretty JSON to stdout. Used by the Commandant to know which fields are
/// valid when authoring a topology.
pub fn schema() -> Result<()> {
    let schema = schemars::schema_for!(TeamTopology);
    println!("{}", serde_json::to_string_pretty(&schema)?);
    Ok(())
}

/// `orchestrator team validate <file>` — parse + validate, never persist.
///
/// Prints `{"valid":true}` on zero violations or
/// `{"valid":false,"violations":[…]}` otherwise.
pub async fn validate(conn: &mut ConnectionManager, file: &Path) -> Result<()> {
    let text = tokio::fs::read_to_string(file).await?;
    let team: TeamTopology = match serde_json::from_str::<TeamTopology>(&text) {
        Ok(t) => t,
        Err(e) => {
            let v = vocabulary_violation_json(&e);
            print_validity_raw(false, &[v]);
            return Ok(());
        }
    };

    let registered_roles = redis_io::list_roles(conn).await?;
    let violations = team_validator::validate(&team, &registered_roles);
    let arr: Vec<_> = violations.iter().map(violation_to_json).collect();
    print_validity_raw(violations.is_empty(), &arr);
    Ok(())
}

/// Synthesize the JSON record for a serde unknown-field / parse error. The
/// `kind` is rendered as `"Vocabulary"` to mark this as the parse-time
/// vocabulary-integrity check (distinct from the runtime `Type` check).
fn vocabulary_violation_json(err: &serde_json::Error) -> serde_json::Value {
    json!({
        "path": "<root>",
        "kind": "Vocabulary",
        "detail": err.to_string(),
    })
}

fn violation_to_json(v: &TeamValidationViolation) -> serde_json::Value {
    json!({
        "path": v.path,
        "kind": format!("{:?}", v.kind),
        "detail": v.detail,
    })
}

fn print_violations_raw(registered: bool, violations: &[serde_json::Value]) {
    let obj = json!({
        "registered": registered,
        "violations": violations,
    });
    println!("{obj}");
}

fn print_validity_raw(valid: bool, violations: &[serde_json::Value]) {
    if valid {
        println!("{}", json!({ "valid": true }));
    } else {
        println!(
            "{}",
            json!({
                "valid": false,
                "violations": violations,
            })
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use orchestrator_types::{MessageEdge, RoleName, RoleRef, TeamName};
    use redis::AsyncCommands;
    use std::io::Write;

    fn test_redis_url() -> Option<String> {
        std::env::var("AGENTRY_TEST_REDIS_URL").ok()
    }

    fn slug() -> String {
        format!(
            "cli_{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        )
    }

    fn write_topology(t: &TeamTopology) -> tempfile::NamedTempFile {
        let body = serde_json::to_string_pretty(t).expect("serialize topology");
        let mut f = tempfile::NamedTempFile::new().expect("tmp");
        f.write_all(body.as_bytes()).expect("write tmp");
        f
    }

    fn rn(s: &str) -> RoleName {
        RoleName(s.into())
    }

    fn rr(s: &str) -> RoleRef {
        RoleRef {
            name: rn(s),
            version: 1,
        }
    }

    fn topo(name: &str, version: u32, role: &str) -> TeamTopology {
        TeamTopology {
            name: TeamName(name.into()),
            version,
            roles: vec![rr(role)],
            message_graph: vec![],
            terminal_role: rr(role),
            max_retries: 0,
        }
    }

    async fn seed_role_v1(conn: &mut ConnectionManager, name: &str) {
        let body = serde_json::json!({"_": "probe"}).to_string();
        let key = format!("agentry:role:{name}:v1");
        let _: () = conn.set(&key, body.as_str()).await.expect("set role");
    }

    async fn cleanup_role(conn: &mut ConnectionManager, name: &str) {
        let key = format!("agentry:role:{name}:v1");
        let _: () = conn.del(&key).await.expect("cleanup role");
    }

    async fn cleanup_team(conn: &mut ConnectionManager, name: &str, version: u32) {
        let key = format!("agentry:team:{name}:v{version}");
        let _: () = conn.del(&key).await.expect("cleanup team");
    }

    #[test]
    fn schema_outputs_valid_json() {
        let schema = schemars::schema_for!(TeamTopology);
        let v = serde_json::to_value(&schema).expect("schema must serialize as JSON");
        let obj = v.as_object().expect("schema root must be a JSON object");
        assert!(!obj.is_empty(), "schema root object must not be empty");
        assert!(
            obj.contains_key("properties"),
            "TeamTopology schema must expose a `properties` map (got keys: {:?})",
            obj.keys().collect::<Vec<_>>()
        );
    }

    #[test]
    fn schema_includes_terminal_role_field() {
        let schema = schemars::schema_for!(TeamTopology);
        let v = serde_json::to_value(&schema).expect("schema must serialize as JSON");
        let props = v
            .get("properties")
            .and_then(|p| p.as_object())
            .expect("TeamTopology schema must have a `properties` object");
        assert!(
            props.contains_key("terminal_role"),
            "TeamTopology schema must include `terminal_role` (got: {:?})",
            props.keys().collect::<Vec<_>>()
        );
    }

    #[tokio::test]
    #[ignore = "requires live Redis (AGENTRY_TEST_REDIS_URL)"]
    async fn register_rejects_unknown_role() {
        let Some(url) = test_redis_url() else { return };
        let mut conn = redis_io::connect(&url).await.expect("connect");
        let s = slug();
        let team_name = format!("zz-cli-{s}");
        // role isn't seeded — registry won't contain it, so register must reject.
        let t = topo(&team_name, 1, &format!("zz-missing-{s}"));
        let f = write_topology(&t);

        let r = register(&mut conn, f.path()).await;
        assert!(r.is_err(), "register must error on validation failure");
        // Key must not have been written.
        let key = format!("agentry:team:{team_name}:v1");
        let raw: Option<String> = conn.get(&key).await.expect("get");
        assert!(raw.is_none(), "register must not persist on violations");
    }

    #[tokio::test]
    #[ignore = "requires live Redis (AGENTRY_TEST_REDIS_URL)"]
    async fn validate_rejects_cycle() {
        let Some(url) = test_redis_url() else { return };
        let mut conn = redis_io::connect(&url).await.expect("connect");
        let s = slug();
        let role_a = format!("zz-cli-a-{s}");
        let role_b = format!("zz-cli-b-{s}");
        seed_role_v1(&mut conn, &role_a).await;
        seed_role_v1(&mut conn, &role_b).await;

        let team_name = format!("zz-cli-cyc-{s}");
        let t = TeamTopology {
            name: TeamName(team_name.clone()),
            version: 1,
            roles: vec![rr(&role_a), rr(&role_b)],
            message_graph: vec![
                MessageEdge {
                    from: rr(&role_a),
                    to: rr(&role_b),
                    permit_overrides_from: None,
                    rework_target: None,
                },
                MessageEdge {
                    from: rr(&role_b),
                    to: rr(&role_a),
                    permit_overrides_from: None,
                    rework_target: None,
                },
            ],
            terminal_role: rr(&role_b),
            max_retries: 0,
        };
        let f = write_topology(&t);
        validate(&mut conn, f.path()).await.expect("validate runs");

        // Validate must not persist anything.
        let key = format!("agentry:team:{team_name}:v1");
        let raw: Option<String> = conn.get(&key).await.expect("get");
        assert!(raw.is_none(), "validate must never persist");

        cleanup_role(&mut conn, &role_a).await;
        cleanup_role(&mut conn, &role_b).await;
    }

    #[tokio::test]
    #[ignore = "requires live Redis (AGENTRY_TEST_REDIS_URL)"]
    async fn register_rejects_duplicate_at_same_version() {
        let Some(url) = test_redis_url() else { return };
        let mut conn = redis_io::connect(&url).await.expect("connect");
        let s = slug();
        let role = format!("zz-cli-dup-{s}");
        seed_role_v1(&mut conn, &role).await;

        let team_name = format!("zz-cli-dup-team-{s}");
        let t = topo(&team_name, 1, &role);
        let f = write_topology(&t);

        register(&mut conn, f.path()).await.expect("first register");
        let again = register(&mut conn, f.path()).await;
        assert!(
            again.is_err(),
            "second register at same (name, version) must error"
        );

        cleanup_team(&mut conn, &team_name, 1).await;
        cleanup_role(&mut conn, &role).await;
    }
}
