//! Role-catalog CLI handlers backing `orchestrator role` subcommands.
//!
//! Mirrors `cli_teams` in shape: each function takes a `&mut ConnectionManager`
//! plus the parsed args, prints structured JSON to stdout, and returns
//! `Result<()>`. The binary glues clap to these. There is no `register`
//! subcommand for roles — roles are engine-seeded only (per the EPIC's Q9
//! directive), so the only CLI surface is list / show / validate.

use crate::{redis_io, Error, Result};
use orchestrator_types::AgentRole;
use redis::aio::ConnectionManager;
use serde_json::json;
use std::path::Path;

/// `orchestrator role list` — print one `{"name":"…","version":N}` per line.
pub async fn list(conn: &mut ConnectionManager) -> Result<()> {
    let pairs = redis_io::list_roles(conn).await?;
    for (name, version) in pairs {
        let line = json!({ "name": name.0, "version": version });
        println!("{line}");
    }
    Ok(())
}

/// `orchestrator role show <name> <version>` — pretty-printed `AgentRole`.
pub async fn show(conn: &mut ConnectionManager, name: &str, version: u32) -> Result<()> {
    let role_name = orchestrator_types::RoleName(name.into());
    let role = redis_io::fetch_role(conn, &role_name, version).await?;
    println!("{}", serde_json::to_string_pretty(&role)?);
    Ok(())
}

/// `orchestrator role schema` — print the JSON schema of `AgentRole`.
///
/// Offline (no Redis). Prints the schema generated by `schemars::schema_for!`
/// as pretty JSON to stdout. Used by the Commandant to know which fields are
/// valid when authoring a role.
pub fn schema() -> Result<()> {
    let schema = schemars::schema_for!(AgentRole);
    println!("{}", serde_json::to_string_pretty(&schema)?);
    Ok(())
}

/// `orchestrator role validate <file>` — parse-only validation. Reads the
/// file, attempts strict deserialization as `AgentRole`. On success prints
/// `{"valid":true,"name":"…","version":N}`. On failure prints
/// `{"valid":false,"error":"…"}` and returns Err so the caller exits non-zero.
/// Does NOT contact Redis.
pub async fn validate(_conn: &mut ConnectionManager, file: &Path) -> Result<()> {
    let text = tokio::fs::read_to_string(file).await?;
    match serde_json::from_str::<AgentRole>(&text) {
        Ok(role) => {
            println!(
                "{}",
                json!({
                    "valid": true,
                    "name": role.name.0,
                    "version": role.version,
                })
            );
            Ok(())
        }
        Err(e) => {
            println!(
                "{}",
                json!({
                    "valid": false,
                    "error": e.to_string(),
                })
            );
            Err(Error::Config(format!("invalid role JSON: {e}")))
        }
    }
}
