//! Team-catalog CLI handlers backing `orchestrator team` subcommands.
//!
//! Each function takes a `&mut ConnectionManager` plus the parsed args, prints
//! structured JSON to stdout, and returns `Result<()>`. The binary glues clap
//! to these — keep them pure (no global state, no exit-on-error). For the
//! register/duplicate path the function returns `Err(Error::Config(...))`
//! after printing so the caller can map it to a non-zero exit.

use crate::team_validator::{self, TeamValidationViolation};
use crate::{redis_io, Error, Result};
use orchestrator_types::{TeamTopology, VersionedRef};
use redis::aio::ConnectionManager;
use serde_json::json;
use std::path::Path;

/// `orchestrator team list` — print one `{"name":"…","version":N}` per line.
pub async fn list(conn: &mut ConnectionManager) -> Result<()> {
    let pairs = redis_io::list_teams(conn).await?;
    for (name, version) in pairs {
        let line = json!({ "name": name.0, "version": version });
        println!("{line}");
    }
    Ok(())
}

/// `orchestrator team show <name> <version>` — pretty-printed `TeamTopology`.
///
/// The serialized output is the full `TeamTopology` shape, which since
/// brief #494 alpha includes the top-level `node_classes` map (when
/// non-empty) and each `message_graph[i].gate_policy` value (when set).
/// Both fields are additive: existing consumers continue to see the
/// pre-#494 keys unchanged.
pub async fn show(conn: &mut ConnectionManager, name: &str, version: u32) -> Result<()> {
    let r = VersionedRef::new(name, version);
    let team = redis_io::fetch_team(conn, &r).await?;
    println!("{}", serde_json::to_string_pretty(&team)?);
    Ok(())
}

/// `orchestrator team register <file>` — parse, validate, atomically register.
///
/// Sequence:
/// 1. Read the file and deserialize it as `TeamTopology` (strict serde —
///    unknown fields are rejected here as a `Vocabulary`-equivalent violation).
/// 2. Fetch the role registry via `redis_io::list_roles`.
/// 3. Run `team_validator::validate`; on any violations, print
///    `{"registered":false,"violations":[…]}` and return Err.
/// 4. `register_team_strict` atomically; print outcome and (on already-exists)
///    return Err so the caller exits non-zero.
pub async fn register(conn: &mut ConnectionManager, file: &Path) -> Result<()> {
    let text = tokio::fs::read_to_string(file).await?;
    let team: TeamTopology = match serde_json::from_str::<TeamTopology>(&text) {
        Ok(t) => t,
        Err(e) => {
            let v = vocabulary_violation_json(&e);
            print_violations_raw(false, &[v]);
            return Err(Error::Config(format!("vocabulary: {e}")));
        }
    };

    let registered_roles = redis_io::list_roles(conn).await?;
    let violations = team_validator::validate(&team, &registered_roles);
    if !violations.is_empty() {
        let arr: Vec<_> = violations.iter().map(violation_to_json).collect();
        print_violations_raw(false, &arr);
        return Err(Error::Config(format!(
            "team {} v{} failed validation: {} violation(s)",
            team.name.0,
            team.version,
            violations.len()
        )));
    }

    match redis_io::register_team_strict(conn, &team).await? {
        redis_io::RegisterOutcome::Registered => {
            println!(
                "{}",
                json!({
                    "registered": true,
                    "name": team.name.0,
                    "version": team.version,
                })
            );
            Ok(())
        }
        redis_io::RegisterOutcome::AlreadyExists => {
            println!(
                "{}",
                json!({
                    "registered": false,
                    "reason": "already_exists",
                    "name": team.name.0,
                    "version": team.version,
                })
            );
            Err(Error::Config(format!(
                "team {} v{} already exists",
                team.name.0, team.version
            )))
        }
    }
}

/// `orchestrator team schema` — print the JSON schema of `TeamTopology`.
///
/// Offline (no Redis). Prints the schema generated by `schemars::schema_for!`
/// as pretty JSON to stdout. Used by the Commandant to know which fields are
/// valid when authoring a topology.
pub fn schema() -> Result<()> {
    let schema = schemars::schema_for!(TeamTopology);
    println!("{}", serde_json::to_string_pretty(&schema)?);
    Ok(())
}

/// `orchestrator team validate <file>` — parse + validate, never persist.
///
/// Prints `{"valid":true}` on zero violations or
/// `{"valid":false,"violations":[…]}` otherwise.
pub async fn validate(conn: &mut ConnectionManager, file: &Path) -> Result<()> {
    let text = tokio::fs::read_to_string(file).await?;
    let team: TeamTopology = match serde_json::from_str::<TeamTopology>(&text) {
        Ok(t) => t,
        Err(e) => {
            let v = vocabulary_violation_json(&e);
            print_validity_raw(false, &[v]);
            return Ok(());
        }
    };

    let registered_roles = redis_io::list_roles(conn).await?;
    let violations = team_validator::validate(&team, &registered_roles);
    let arr: Vec<_> = violations.iter().map(violation_to_json).collect();
    print_validity_raw(violations.is_empty(), &arr);
    Ok(())
}

/// Synthesize the JSON record for a serde unknown-field / parse error. The
/// `kind` is rendered as `"Vocabulary"` to mark this as the parse-time
/// vocabulary-integrity check (distinct from the runtime `Type` check).
fn vocabulary_violation_json(err: &serde_json::Error) -> serde_json::Value {
    json!({
        "path": "<root>",
        "kind": "Vocabulary",
        "detail": err.to_string(),
    })
}

fn violation_to_json(v: &TeamValidationViolation) -> serde_json::Value {
    json!({
        "path": v.path,
        "kind": format!("{:?}", v.kind),
        "detail": v.detail,
    })
}

fn print_violations_raw(registered: bool, violations: &[serde_json::Value]) {
    let obj = json!({
        "registered": registered,
        "violations": violations,
    });
    println!("{obj}");
}

fn print_validity_raw(valid: bool, violations: &[serde_json::Value]) {
    if valid {
        println!("{}", json!({ "valid": true }));
    } else {
        println!(
            "{}",
            json!({
                "valid": false,
                "violations": violations,
            })
        );
    }
}
